# Generated by Django 4.1.6 on 2023-02-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alcohol_percentage', models.DecimalField(decimal_places=1, max_digits=2)),
                ('color', models.CharField(max_length=255)),
                ('aroma_choice', models.CharField(choices=[('BITTER', 'Bitter'), ('SWEET', 'Sweet'), ('SOUR', 'Sour'), ('BITTER_SOUR', 'Bitter-Sour'), ('BITTER_SWEET', 'Bitter-Sweet'), ('SWEET_SOUR', 'Sweer-Sour'), ('NO_AROMA', 'No aroma')], max_length=255)),
                ('water', models.DecimalField(decimal_places=2, max_digits=3)),
                ('barley', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hop', models.DecimalField(decimal_places=2, max_digits=3)),
                ('yeast', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(max_length=5)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(max_length=50)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.beer')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='BeerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.beertype'),
        ),
        migrations.AddField(
            model_name='beer',
            name='Manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
    ]
