# Generated by Django 4.1.6 on 2023-02-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_beer_beertype_review_beer_beertype_beer_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
    ]
