# Generated by Django 4.1.6 on 2023-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_manufacturer_postal_code_remove_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='barley',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='beer',
            name='hop',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='beer',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='beer',
            name='yeast',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
