# Generated by Django 4.1.6 on 2023-02-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_beer_barley_alter_beer_hop_alter_beer_water_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='barley',
            new_name='barley_percentage',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='hop',
            new_name='hop_percentage',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='water',
            new_name='water_percentage',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='yeast',
            new_name='yeast_percentage',
        ),
    ]
