# Generated by Django 4.1.6 on 2023-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_barley_beer_barley_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='BeerType',
            new_name='beer_type',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='beer',
            name='aroma_choice',
            field=models.CharField(choices=[('BT', 'Bitter'), ('SW', 'Sweet'), ('SO', 'Sour'), ('BT-SO', 'Bitter-Sour'), ('BT-SW', 'Bitter-Sweet'), ('SW-SO', 'Sweer-Sour'), ('No aroma', 'No aroma')], max_length=255),
        ),
    ]
