# Generated by Django 4.1.6 on 2023-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_beertype_beer_beer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='postal_code',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
