# Generated by Django 4.1.6 on 2023-02-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manufacturer_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
