# Generated by Django 4.1.6 on 2023-03-14 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_beer_current_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='current_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
